logging:
  config: classpath:logback-spring.xml
atp:
  devMode:
    peerName: peer
    ordererName: orderer
#    peerUrl: grpc://192.168.31.128:7051
#    peerUrl: grpc://8.133.190.119:7051
    peerUrl: grpc://127.0.0.1:7051
#    peerUrl: grpc://10.177.88.201:7051
#    ordererUrl: grpc://192.168.31.128:7050
#    ordererUrl: grpc://8.133.190.119:7050
    ordererUrl: grpc://127.0.0.1:7050
#    ordererUrl: grpc://10.177.88.201:7050
    channelName: myc
    baseUrl: http://101.201.49.180:8000

  path:
    dabeUser: atp/user/
    privateKey: atp/priKey/
    publicKey: atp/pubKey/
    cert: atp/cert/
    shareData: atp/data/
    encryptData: atp/data/enc/
    cipherData: atp/data/cipher/

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
